[features]
seeds = false
[programs.localnet]
mercurial_dynamic_amm_sdk = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/guantian/.config/solana/id.json"

[workspace]
members = [
    "programs/dynamic-amm",
    "programs/dynamic-vault",
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.30.1"