[workspace]
members = [
    "programs/*",
    "rust-client",
    "dynamic-amm-quote"
]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["Andrew"]
edition = "2021"

[profile.release]
overflow-checks = true